apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: spider
  name: cron-spider-affiliation
spec:
  schedule: "00 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: spider-account
          containers:
          - name: cms-htcondor-es
            image: cronosnull/cms_htcondor_es:0.3
            args:
            - /bin/sh
            - -c
            - echo "run k8s_affiliation_cache.sh"; /cms-htcondor-es/k8s_affiliation_cache.sh $AFFILIATION_DIR_LOCATION; echo "ls -al /etc/affiliations"; ls -al AFFILIATION_DIR_LOCATION
            tty: true
            stdin: true
            lifecycle:
              postStart:
                exec:
                  command:
                  - bash
                  - -c
                  - sudo chmod 0777 $AFFILIATION_DIR_LOCATION; sudo chown 1414:1414 $AFFILIATION_DIR_LOCATION; ls -al $AFFILIATION_DIR_LOCATION
            env:
              - name: AFFILIATION_DIR_LOCATION
                value: /cms_shared/affiliation_dir.json
              - name: CELERY_BROKER_URL
                value: redis://$(REDIS_SERVICE_HOST):$(REDIS_SERVICE_PORT_6379)/0
              - name: CELERY_RESULT_BACKEND
                value: redis://$(REDIS_SERVICE_HOST):$(REDIS_SERVICE_PORT_6379)/1
              - name: CELERY_TEST
                value: '"true"'
              - name: C_FORCE_ROOT
                value: '"true"'
              - name: PYTHONPATH
                value: /cms-htcondor-es/src:$PYTHONPATH
              - name: REQUESTS_CA_BUNDLE
                value: /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
            volumeMounts: 
              - mountPath: /cms_shared
                name: shared-spider
          volumes:
            - name: shared-spider
              emptyDir: {}
        #PROD#persistentVolumeClaim:
        #PROD#  claimName: affilations-cephfs-claim
          restartPolicy: Never
          securityContext:
            fsGroup: 1414