apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: affilations-cephfs-claim
  namespace: spider
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: meyrin-cephfs